kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        tier: frontend
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}

