kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None  