apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.database.resourceName }}
spec:
  image: {{ .Values.database.image }}
  postgresVersion: {{ .Values.database.postgresVersion }}
  openshift: true
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.database.storage }}
  users:
    - name: {{ .Values.database.user }}
      databases:
        - {{ .Values.database.dbName }}            
  backups:
    pgbackrest:
      image: {{ .Values.database.backup.image }}
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.database.backup.storage }}