kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        tier: backend
    spec:
      volumes:
        - name: secret
          secret:
            secretName: {{ .Values.envSecret.name }}
            defaultMode: 420
            items:
            - key: .env
              path: .env
      containers:
        - name: {{ .Values.deployment.name }}
          image: >-
            {{ .Values.deployment.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          # readinessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - '-sSf'
          #       - 'http://localhost:8080/health/ready'       
          env:
          - name: AB_JOLOKIA_OFF
            value: {{ .Values.deployment.env.abJolokiaOff | quote }}
          - name: AB_PROMETHEUS_OFF
            value: {{ .Values.deployment.env.abPrometheusOff | quote }}
          - name: JAVA_MAX_MEM_RATIO
            value: {{ .Values.deployment.env.javaMaxMemRatio | quote }}
          - name: JAVA_INIT_MEM_RATIO
            value: {{ .Values.deployment.env.javaInitMemRatio | quote }}            
          - name: JAVA_OPTIONS
            value: >-
              {{ .Values.deployment.env.javaOptions }}
          - name: TZ
            value: {{ .Values.deployment.env.timeZone }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.resourceName }}-pguser-{{ .Values.database.user }}
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.resourceName }}-pguser-{{ .Values.database.user }}
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: '{{ .Values.database.resourceName }}-pguser-{{ .Values.database.user }}'
                key: host                
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
          volumeMounts:
            - name: secret
              mountPath: /deployments/.env
              subPath: .env

