kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-mega-dev
  namespace: mega-dev
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: mega-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-mega-test
  namespace: mega-test
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: mega-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-mega-prod
  namespace: mega-prod
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: mega-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit