apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mega
  namespace: mega-cicd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'mega-dev'
      server: '*'
    - namespace: 'mega-test'
      server: '*'
    - namespace: 'mega-prod'
      server: '*'
  sourceRepos:
    - '*'